#!/usr/bin/env bash

# check docker image for building
if [ "$(docker images -q iwebpp-bld:3.1 2> /dev/null)" == "" ]; then
  echo "Build Docker image as iwebpp-bld:3.1"
  docker image build --rm --network host --compress -t iwebpp-bld:3.1 -f ./Dockerfile.bld .
fi

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t --rm --network host iwebpp-bld:3.1 $@
else
  echo "Start building ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t --rm --network host iwebpp-bld:3.1 \
  bash -c "npm i --only=prod && ./tools/genSrvKey.bash 51dese.com"
fi
