#!/usr/bin/env bash

# check docker image for building
if [ "$(docker images -q iwebpp-bld:16.04 2> /dev/null)" == "" ]; then
  echo "Build Docker image as iwebpp-bld:16.04"
  docker image build --compress -t iwebpp-bld:16.04 -f ./Dockerfile.bld .
fi

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t --rm --network host iwebpp-bld:16.04 $@
fi
