#!/usr/bin/env bash

# check docker image for packaging 
if [ "$(docker images -q iwebpp:16.04 2> /dev/null)" == "" ]; then
  echo "Build Docker image as iwebpp:16.04"
  docker image build --compress -t iwebpp:16.04 -f ./Dockerfile.pkg .
fi

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  iwebpp:16.04 $@
else
  echo "Start services ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  -p 51686:51686/udp \
  -p 51868:51868/udp \
  -p 51866:51866/udp \
  -p 51688:51688/udp \
  -p 51688:51688/tcp \
  --name iwebpp.io-controller \
  iwebpp:16.04
fi
