#
# iWebPP.io packaging Dockerfile
#
# https://github.com/InstantWebP2P/iwebpp.io-controller
#

# Pull base image.
FROM httpp:16.04

# Install.
RUN \
 apt-get -y update && \
 apt-get install -y openssl

# Add files.
COPY . /appins/

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /appins

# Expose ports
EXPOSE 51686/udp
EXPOSE 51868/udp
EXPOSE 51866/udp
EXPOSE 51688/udp
EXPOSE 51688/tcp

# Define default command.
CMD ["node", "./bin/srv.js"]
