#
# AppNet.io building Dockerfile
#
# https://github.com/InstantWebP2P/appnet.io-controller
# Copyright (c) 2020 Tom Zhou<appnet.link@gmail.com>

# Pull base image.
FROM httpp:0.8

# Install.
RUN \
 apt-get -y update && \
 apt-get install -y python g++ make openssl vim

# Add files.

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["bash"]
